---
- name: Install Apache and MariaDB on a Linux server
  hosts: webServers
  become: yes
  vars:
    mariadb_secure_installation: false  # Define the variable here
    ansible_python_interpreter: /usr/bin/python3  

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Secure MariaDB installation
      block:
        - name: Set password for 'vagrant' user in MariaDB
          mysql_user:
            login_user: vagrant
            login_password: 'vagrant'
            name: vagrant
            password: 'Passw0rd'  # Uus parool
            host_all: yes

        - name: Remove anonymous users
          mysql_user:
            login_user: vagrant
            login_password: 'Passw0rd'
            name: ''
            host_all: yes
            state: absent

        - name: Disallow root login remotely
          mysql_user:
            login_user: vagrant
            login_password: 'Passw0rd'
            name: vagrant
            host: '%'
            state: absent

        - name: Remove test database
          mysql_db:
            login_user: vagrant
            login_password: 'Passw0rd'
            name: test
            state: absent
      when: mariadb_secure_installation

    - name: Ensure MariaDB service is running
      service:
        name: mariadb
        state: started
